language: csharp
mono: alpha
solution: KNX.net.sln
sudo: required
before_script:
  - chmod a+x travis-install-eibd.sh
  - ./travis-install-eibd.sh
install:
  - nuget restore KNX.net.sln
  - nuget install NUnit.Console -ExcludeVersion -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release KNX.net.sln
  - mono ./testrunner/NUnit.ConsoleRunner/tools/nunit3-console.exe ./tests/KNXLibTests/bin/Release/KNXLibTests.dll --labels=On --nocolor --verbose --workers=1 --full --result:"./nunit-result.xml;format=nunit2"
